{% set name = "mpark.variant" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mpark/variant
  git_tag: v{{ version }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - git    
    - cmake
    - make   # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}

about:
  home: https://github.com/mpark/variant
  summary: "MPark.Variant is an implementation of C++17 std::variant for C++11/14/17."
  license: Boost
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bkreider
